#version=0.1.0
#TODO: 
# Transfer connections to YAML
name: test

objects:
  schema: 
  - online_sales
  - public

  tables:
  - Elysium.FINGAM_Transactions
  - Elysium.FINGAM_Orders
  - Elysium.FINGAM_Executions_T
  - Elysium.FINGAM_Enrichments
  - Elysium.FINGAM_Enrichments_Rejected
  - Elysium.FINGAM_ComplexTrades
  - Elysium.FINGAM_Orders_Rejected
  - Elysium.FINSECMM_Orders
  - Elysium.FINSECMM_Transactions
  - Elysium.FINSECMM_Executions_T
  - Elysium.FINSECMM_Busts_T
  - Elysium.FINSECMM_Quotes
  - Elysium.FINSECMM_Enrichments
  - Elysium.FINSECMM_ComplexTrades
  - Elysium.TKey_Mapping_T
  - Elysium.TKey_Updates
  - Elysium.BookmarkStore
  - Elysium.Sweeper_Bookmark
  - Elysium.TKEY_LATEST_MAPPINGS_T
  - Elysium.TKey_Cancel_T
  - Elysium.TKey_Cancel_All_T
  - Compliance.DeskLevelUser
  - Compliance.DeskLevelUserDB
  - Compliance.OverTheEdgeUser
  - Compliance.OverTheEdgeUserDB
  - sandbox.TKEY_LATEST_MAPPINGS_T
  - sandbox.BookmarkStore_TO_DROP2
  - sandbox.C
  - sandbox.C1
  - sandbox.CG
  - sandbox.COM
  - sandbox.SL
  - sandbox.BookmarkStore_TO_DROP
