
CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Transactions
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionType varchar(128),
    DiscretionaryPrice float,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    ExecPrice float,
    ExecQuantity float,
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalExecutionID varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsSolicited int,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OTCIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSystem varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RecordType varchar(128),
    RegulatoryTradeID varchar(128),
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    TransactionTime int,
    TransactionTimeNsecs int,
    TxID int,
    "UUID" varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    ExecQuantityType varchar(128),
    ExecPriceType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    TradeDate date,
    CancelOrderID varchar(128),
    ReplaceOrderID varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    ExecPriceCurrencyID int,
    IsInternal int,
    OrderAction varchar(128),
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ShortSellReportingExempt int,
    SwapIndicator int,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    DirectedOrderIndicator int,
    LinkedTransactionType varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    TransactionToBeCleared int,
    OriginatorSubsystem varchar(128),
    financeJoinIDType varchar(128),
    OTCAPAIndicator varchar(128),
    ConnectionUKey int,
    ConnectionName varchar(128),
    IsEstimatedPrice int,
    BookingEligible int,
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID int,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    TradeType varchar(128),
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend INT
);


CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Busts_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    ExternalExecutionID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TransactionTime int,
    TransactionTimeNsecs int,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    SequenceInstance varchar(128),
    SequenceNumber int,
    AgencyClientID int,
    AggregationValue varchar(128),
    BookingEligible int,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBData varchar(8000),
    financePBType varchar(128),
    financeQuantity float,
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    CommissionType varchar(128),
    CommissionValue float,
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DirectedOrderIndicator int,
    DiscretionaryPrice float,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice int,
    IsInternal int,
    IsSolicited int,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderUUID varchar(128),
    OriginatorLocation varchar(128),
    OTCAPAIndicator varchar(128),
    OTCIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    SwapIndicator int,
    TradeDate date,
    TradeType varchar(128),
    TransactionToBeCleared int,
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Orders
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    VersionNumber varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    "UUID" varchar(128) NOT NULL,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    CancelOrderID varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DiscretionaryPrice float,
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalOrderID varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ReplaceOrderID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePBData varchar(8000),
    FundDeskOrderAllocations varchar(8000),
    InternalOrderAckID varchar(128),
    InternalOrderAmendID varchar(128),
    InternalOrderCancelID varchar(128),
    OrderDate date,
    OrderEventReason varchar(128),
    OrderEventType varchar(128),
    OrderState varchar(128),
    OrderUUID varchar(128),
    ReplacesOrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    SwapIndicator int,
    OriginalOrderUUID varchar(128),
    RootOrderUUID varchar(128),
    TradeDate date,
    ElysiumRevisionNumber int
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Executions_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingEligible int,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DirectedOrderIndicator int,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice int,
    IsInternal int,
    IsSolicited int,
    LastCapacity varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    SwapIndicator int,
    TradeDate date,
    TransactionTime int,
    TransactionTimeNsecs int,
    TransactionToBeCleared int,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID int,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend INT
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Enrichments
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    RecordType varchar(128),
    "UUID" varchar(128),
    EventTime int NOT NULL,
    OriginatorSystem varchar(128),
    VersionNumber varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    OriginatorSubsystem varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    WaiverIndicator varchar(128),
    BookingEligible int,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DirectedOrderIndicator int,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsEstimatedPrice int,
    IsInternal int,
    IsSolicited int,
    LastCapacity varchar(128),
    LinkID varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    SwapIndicator int,
    TradeDate date,
    TransactionTime int,
    TransactionTimeNsecs int,
    TransactionToBeCleared int,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID int,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend INT
);


CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Enrichments_Rejected
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    CONTENT varchar(65000),
    REJECT_INDEX int NOT NULL
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINSECMM_Quotes
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EventTime int NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    ElysiumStartDateTime timestamptz,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    financeDeskType varchar(128),
    financeDesk varchar(128),
    "UUID" varchar(128),
    AskPrice float,
    AskQuantity float,
    BidPrice float,
    BidQuantity float,
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ComplexAllocation varchar(8000),
    ComplexAskPrice float,
    ComplexAskQuantity float,
    ComplexBidPrice float,
    ComplexBidQuantity float,
    CurrencyID int,
    EventTimeNsecs int,
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalQuoteAmendID varchar(128),
    InternalQuoteCancellationID varchar(128),
    InternalQuoteID varchar(128),
    IsAnnounced int,
    IsDoubleSided int,
    IsSolicited int,
    OriginalQuoteUUID varchar(128),
    QuoteType varchar(128),
    ReceiveTime int,
    ReplacesQuoteUUID varchar(128),
    RootQuoteUUID varchar(128),
    SpreadUID varchar(128),
    TiedDelta float,
    TiedPrice float,
    VenueIdentifier varchar(128),
    VenueType varchar(128)
);


CREATE TABLE IF NOT EXISTS VHTEST.FINSECMM_ComplexTrades
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EventTime int NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    ElysiumStartDateTime timestamptz,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    financeDeskType varchar(128),
    financeDesk varchar(128),
    "UUID" varchar(128),
    EventTimeNsecs int,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    InternalComplexExecutionID varchar(128),
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TradeDate date
);

CREATE TABLE IF NOT EXISTS VH_TEST.TKey_Updates
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    VersionNumber varchar(128),
    "UUID" varchar(128),
    EventTime int NOT NULL,
    RecordType varchar(128),
    TxID int,
    TxVersionNumber int,
    InternalExecutionID varchar(128),
    OriginatorSystem varchar(128),
    BookingDate date,
    TxnVersionNumber int,
    TxnVersionTimestamp int,
    TxnVersionStatus varchar(128),
    FirmID int,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    OriginatorSubsystem varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber int,
    POExecutionID varchar(128)
)


CREATE TABLE IF NOT EXISTS VH_TEST.TKey_Mapping_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz,
    "UUID" varchar(128),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingDate date,
    EventTime int NOT NULL,
    FirmID int,
    InternalExecutionID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TxID int,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber int,
    POExecutionID varchar(128)
);"DBOPERATIONS3"


CREATE TABLE IF NOT EXISTS VH_TEST.TKey_Cancel_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz,
    "UUID" varchar(128),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingDate date,
    EventTime int NOT NULL,
    FirmID int,
    InternalExecutionID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TxID int,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber int,
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS VH_TEST.TKey_Cancel_All_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz,
    "UUID" varchar(128),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingDate date,
    EventTime int NOT NULL,
    FirmID int,
    InternalExecutionID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TxID int,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber int,
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS VH_TEST.BookmarkStore
(
    flow varchar(128) NOT NULL,
    source varchar(128) NOT NULL,
    version varchar(16) NOT NULL,
    batchID int NOT NULL,
    recordCount int NOT NULL,
    publisher varchar(512) NOT NULL,
    bookmark varchar(1024) NOT NULL,
    lastSeen int NOT NULL,
    active boolean DEFAULT true,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_Transactions
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionType varchar(128),
    DiscretionaryPrice float,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    ExecPrice float,
    ExecQuantity float,
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalExecutionID varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsSolicited int,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OTCIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSystem varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RecordType varchar(128),
    RegulatoryTradeID varchar(128),
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    TransactionTime int,
    TransactionTimeNsecs int,
    TxID int,
    "UUID" varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    ExecQuantityType varchar(128),
    ExecPriceType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    TradeDate date,
    CancelOrderID varchar(128),
    ReplaceOrderID varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    ExecPriceCurrencyID int,
    IsInternal int,
    OrderAction varchar(128),
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ShortSellReportingExempt int,
    SwapIndicator int,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    DirectedOrderIndicator int,
    LinkedTransactionType varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    TransactionToBeCleared int,
    OriginatorSubsystem varchar(128),
    financeJoinIDType varchar(128),
    OTCAPAIndicator varchar(128),
    ConnectionUKey int,
    ConnectionName varchar(128),
    IsEstimatedPrice int,
    BookingEligible int,
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID int,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    TradeType varchar(128),
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend int
);


CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_Orders
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    VersionNumber varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    "UUID" varchar(128) NOT NULL,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    CancelOrderID varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DiscretionaryPrice float,
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalOrderID varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ReplaceOrderID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePBData varchar(8000),
    FundDeskOrderAllocations varchar(8000),
    InternalOrderAckID varchar(128),
    InternalOrderAmendID varchar(128),
    InternalOrderCancelID varchar(128),
    OrderDate date,
    OrderEventReason varchar(128),
    OrderEventType varchar(128),
    OrderState varchar(128),
    OrderUUID varchar(128),
    ReplacesOrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    SwapIndicator int,
    OriginalOrderUUID varchar(128),
    RootOrderUUID varchar(128),
    TradeDate date,
    ElysiumRevisionNumber int
);


CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_Executions_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingEligible int,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DirectedOrderIndicator int,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice int,
    IsInternal int,
    IsSolicited int,
    LastCapacity varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    SwapIndicator int,
    TradeDate date,
    TransactionTime int,
    TransactionTimeNsecs int,
    TransactionToBeCleared int,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID int,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend int
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_Enrichments
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    RecordType varchar(128),
    "UUID" varchar(128),
    EventTime int NOT NULL,
    OriginatorSystem varchar(128),
    VersionNumber varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    OriginatorSubsystem varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    WaiverIndicator varchar(128),
    BookingEligible int,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DirectedOrderIndicator int,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsEstimatedPrice int,
    IsInternal int,
    IsSolicited int,
    LastCapacity varchar(128),
    LinkID varchar(128),
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    SwapIndicator int,
    TradeDate date,
    TransactionTime int,
    TransactionTimeNsecs int,
    TransactionToBeCleared int,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID int,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber int,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend int
);

CREATE TABLE VH_TEST.FINGAM_Enrichments_Rejected
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    CONTENT varchar(64256),
    REJECT_INDEX int NOT NULL,
    CONSTRAINT C_PRIMARY PRIMARY KEY (ID) DISABLED
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_Busts_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    EventTime int NOT NULL,
    EventTimeNsecs int,
    ExternalExecutionID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TransactionTime int,
    TransactionTimeNsecs int,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    SequenceInstance varchar(128),
    SequenceNumber int,
    AgencyClientID int,
    AggregationValue varchar(128),
    BookingEligible int,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID int,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBData varchar(8000),
    financePBType varchar(128),
    financeQuantity float,
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    CommissionCurrencyID int,
    CommissionData varchar(8000),
    CommissionType varchar(128),
    CommissionValue float,
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey int,
    DirectedOrderIndicator int,
    DiscretionaryPrice float,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID int,
    FXBuyQuantity float,
    FXSellCurrencyID int,
    FXSellQuantity float,
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice int,
    IsInternal int,
    IsSolicited int,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkedTransactionCount int,
    LinkedTransactionIndex int,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderUUID varchar(128),
    OriginatorLocation varchar(128),
    OTCAPAIndicator varchar(128),
    OTCIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt int,
    Side varchar(128),
    SwapIndicator int,
    TradeDate date,
    TradeType varchar(128),
    TransactionToBeCleared int,
    ElysiumRevisionNumber int,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID int,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend int
);

CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_ComplexTrades
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EventTime int NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    ElysiumStartDateTime timestamptz,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    financeDeskType varchar(128),
    financeDesk varchar(128),
    "UUID" varchar(128),
    EventTimeNsecs int,
    ExecPrice float,
    ExecPriceCurrencyID int,
    ExecPriceType varchar(128),
    InternalComplexExecutionID varchar(128),
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TradeDate date
);


CREATE TABLE IF NOT EXISTS VH_TEST.FINGAM_Orders_Rejected
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP(),
    CONTENT varchar(65000),
    REJECT_INDEX int NOT NULL
);

CREATE TABLE IF NOT EXISTS VH_TEST.TKEY_LATEST_MAPPINGS_T
(
    ID int NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    TxID int NOT NULL,
    "UUID" varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    EventTime int NOT NULL,
    BookingDate date,
    FirmID int,
    InternalExecutionID varchar(128),
    OriginatorSystem varchar(128),
    OriginatorSubsystem varchar(128),
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS VH_TEST.BookmarkStore_TO_DROP2
(
    flow varchar(128) NOT NULL,
    source varchar(128) NOT NULL,
    publisher varchar(32) NOT NULL,
    bookmark varchar(64) NOT NULL,
    batchId int NOT NULL,
    lastSeen int NOT NULL
)

CREATE TABLE IF NOT EXISTS VH_TEST.C
(
    S int,
    F int
);


CREATE TABLE IF NOT EXISTS VH_TEST.C1
(
    S int,
    F int
);

CREATE TABLE IF NOT EXISTS VH_TEST.CG
(
    C int,
    CG varchar(2)
);

CREATE TABLE IF NOT EXISTS VH_TES.COM
(
    S int,
    F int,
    C int
);


CREATE TABLE IF NOT EXISTS VH_TES.BookmarkStore_TO_DROP
(
    flow varchar(128) NOT NULL,
    source varchar(128) NOT NULL,
    publisher varchar(32) NOT NULL,
    bookmark varchar(64) NOT NULL,
    batchId int NOT NULL,
    lastSeen int NOT NULL,
    active boolean NOT NULL DEFAULT true
);


--Compliance
CREATE TABLE IF NOT EXISTS VH_TEST.DeskLevelUser
(
    UserName varchar(30) NOT NULL,
    FullName varchar(128) NOT NULL,
    DeskCode int NOT NULL,
    DeskUKEY varchar(128) NOT NULL,
    DeskNAME varchar(128) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);


CREATE TABLE IF NOT EXISTS VH_TEST.OverTheEdgeUser
(
    UserName varchar(30) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);

CREATE TABLE VH_TEST.OverTheEdgeUserDB
(
    UserName varchar(30) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);


CREATE TABLE VH_TEST.DeskLevelUserDB
(
    UserName varchar(30) NOT NULL,
    FullName varchar(128) NOT NULL,
    DeskCode int NOT NULL,
    DeskUKEY varchar(128) NOT NULL,
    DeskNAME varchar(128) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);
