CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Transactions
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionType varchar(128),
    DiscretionaryPrice float,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    ExecPrice float,
    ExecQuantity float,
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalExecutionID varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsSolicited bigint,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OTCIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSystem varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RecordType varchar(128),
    RegulatoryTradeID varchar(128),
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    TxID bigint,
    "UUID" varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    ExecQuantityType varchar(128),
    ExecPriceType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    TradeDate date,
    CancelOrderID varchar(128),
    ReplaceOrderID varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    ExecPriceCurrencyID bigint,
    IsInternal bigint,
    OrderAction varchar(128),
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ShortSellReportingExempt bigint,
    SwapIndicator bigint,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    DirectedOrderIndicator bigint,
    LinkedTransactionType varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    TransactionToBeCleared bigint,
    OriginatorSubsystem varchar(128),
    financeJoinIDType varchar(128),
    OTCAPAIndicator varchar(128),
    ConnectionUKey bigint,
    ConnectionName varchar(128),
    IsEstimatedPrice bigint,
    BookingEligible bigint,
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    TradeType varchar(128),
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Busts_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    ExternalExecutionID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    BookingEligible bigint,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBData varchar(8000),
    financePBType varchar(128),
    financeQuantity float,
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    CommissionType varchar(128),
    CommissionValue float,
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DirectedOrderIndicator bigint,
    DiscretionaryPrice float,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice bigint,
    IsInternal bigint,
    IsSolicited bigint,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderUUID varchar(128),
    OriginatorLocation varchar(128),
    OTCAPAIndicator varchar(128),
    OTCIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    SwapIndicator bigint,
    TradeDate date,
    TradeType varchar(128),
    TransactionToBeCleared bigint,
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Orders
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    VersionNumber varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    "UUID" varchar(128) NOT NULL,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    CancelOrderID varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DiscretionaryPrice float,
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalOrderID varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ReplaceOrderID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePBData varchar(8000),
    FundDeskOrderAllocations varchar(8000),
    InternalOrderAckID varchar(128),
    InternalOrderAmendID varchar(128),
    InternalOrderCancelID varchar(128),
    OrderDate date,
    OrderEventReason varchar(128),
    OrderEventType varchar(128),
    OrderState varchar(128),
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    SwapIndicator bigint,
    OriginalOrderUUID varchar(128),
    RootOrderUUID varchar(128),
    TradeDate date,
    ElysiumRevisionNumber bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Executions_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingEligible bigint,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DirectedOrderIndicator bigint,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice bigint,
    IsInternal bigint,
    IsSolicited bigint,
    LastCapacity varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    SwapIndicator bigint,
    TradeDate date,
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    TransactionToBeCleared bigint,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Enrichments
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    RecordType varchar(128),
    "UUID" varchar(128),
    EventTime bigint NOT NULL,
    OriginatorSystem varchar(128),
    VersionNumber varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    OriginatorSubsystem varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    WaiverIndicator varchar(128),
    BookingEligible bigint,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DirectedOrderIndicator bigint,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsEstimatedPrice bigint,
    IsInternal bigint,
    IsSolicited bigint,
    LastCapacity varchar(128),
    LinkID varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    SwapIndicator bigint,
    TradeDate date,
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    TransactionToBeCleared bigint,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate DATE,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Enrichments_Rejected
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONTENT varchar(64000),
    REJECT_INDEX bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_Quotes
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EventTime bigint NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    ElysiumStartDateTime timestamptz,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    financeDeskType varchar(128),
    financeDesk varchar(128),
    "UUID" varchar(128),
    AskPrice float,
    AskQuantity float,
    BidPrice float,
    BidQuantity float,
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ComplexAllocation varchar(8000),
    ComplexAskPrice float,
    ComplexAskQuantity float,
    ComplexBidPrice float,
    ComplexBidQuantity float,
    CurrencyID bigint,
    EventTimeNsecs bigint,
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalQuoteAmendID varchar(128),
    InternalQuoteCancellationID varchar(128),
    InternalQuoteID varchar(128),
    IsAnnounced bigint,
    IsDoubleSided bigint,
    IsSolicited bigint,
    OriginalQuoteUUID varchar(128),
    QuoteType varchar(128),
    ReceiveTime bigint,
    ReplacesQuoteUUID varchar(128),
    RootQuoteUUID varchar(128),
    SpreadUID varchar(128),
    TiedDelta float,
    TiedPrice float,
    VenueIdentifier varchar(128),
    VenueType varchar(128)
);

CREATE TABLE IF NOT EXISTS Elysium.FINSECMM_ComplexTrades
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EventTime bigint NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    ElysiumStartDateTime timestamptz,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    financeDeskType varchar(128),
    financeDesk varchar(128),
    "UUID" varchar(128),
    EventTimeNsecs bigint,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    InternalComplexExecutionID varchar(128),
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TradeDate date
);

CREATE TABLE IF NOT EXISTS Elysium.TKey_Updates
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    VersionNumber varchar(128),
    "UUID" varchar(128),
    EventTime bigint NOT NULL,
    RecordType varchar(128),
    TxID bigint,
    TxVersionNumber bigint,
    InternalExecutionID varchar(128),
    OriginatorSystem varchar(128),
    BookingDate date,
    TxnVersionNumber bigint,
    TxnVersionTimestamp bigint,
    TxnVersionStatus varchar(128),
    FirmID bigint,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    OriginatorSubsystem varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber bigint,
    POExecutionID varchar(128)
);


CREATE TABLE IF NOT EXISTS Elysium.TKey_Mapping_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz,
    "UUID" varchar(128),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingDate date,
    EventTime bigint NOT NULL,
    FirmID bigint,
    InternalExecutionID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TxID bigint,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber bigint,
    POExecutionID varchar(128)
);


CREATE TABLE IF NOT EXISTS Elysium.TKey_Cancel_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz,
    "UUID" varchar(128),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingDate date,
    EventTime bigint NOT NULL,
    FirmID bigint,
    InternalExecutionID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TxID bigint,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber bigint,
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS Elysium.TKEY_LATEST_MAPPINGS_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    TxID bigint NOT NULL,
    "UUID" varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    EventTime bigint NOT NULL,
    BookingDate date,
    FirmID bigint,
    InternalExecutionID varchar(128),
    OriginatorSystem varchar(128),
    OriginatorSubsystem varchar(128),
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS Elysium.TKey_Cancel_All_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz,
    "UUID" varchar(128),
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingDate date,
    EventTime bigint NOT NULL,
    FirmID bigint,
    InternalExecutionID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TxID bigint,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    ElysiumRevisionNumber bigint,
    POExecutionID varchar(128)
);

CREATE TABLE IF NOT EXISTS Elysium.BookmarkStore
(
    flow varchar(128) NOT NULL,
    source varchar(128) NOT NULL,
    version varchar(16) NOT NULL,
    batchID bigint NOT NULL,
    recordCount bigint NOT NULL,
    publisher varchar(512) NOT NULL,
    bookmark varchar(1024) NOT NULL,
    lastSeen bigint NOT NULL,
    active boolean DEFAULT true,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Transactions
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionType varchar(128),
    DiscretionaryPrice float,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    ExecPrice float,
    ExecQuantity float,
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalExecutionID varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsSolicited bigint,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OTCIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSystem varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RecordType varchar(128),
    RegulatoryTradeID varchar(128),
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    TxID bigint,
    "UUID" varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    ExecQuantityType varchar(128),
    ExecPriceType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    TradeDate date,
    CancelOrderID varchar(128),
    ReplaceOrderID varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    ExecPriceCurrencyID bigint,
    IsInternal bigint,
    OrderAction varchar(128),
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ShortSellReportingExempt bigint,
    SwapIndicator bigint,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    DirectedOrderIndicator bigint,
    LinkedTransactionType varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    TransactionToBeCleared bigint,
    OriginatorSubsystem varchar(128),
    financeJoinIDType varchar(128),
    OTCAPAIndicator varchar(128),
    ConnectionUKey bigint,
    ConnectionName varchar(128),
    IsEstimatedPrice bigint,
    BookingEligible bigint,
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    TradeType varchar(128),
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Orders
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    VersionNumber varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    "UUID" varchar(128) NOT NULL,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    CancelOrderID varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DiscretionaryPrice float,
    ExecutionInstructions varchar(256),
    ExpiresAt varchar(128),
    ExternalOrderID varchar(128),
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InternalOrderID varchar(128),
    LimitPrice float,
    LinkID varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderType varchar(128),
    OriginatorCapacity varchar(128),
    OriginatorLocation varchar(128),
    ParentOrderID varchar(128),
    ParentOrderIdSource varchar(128),
    PeggedSpread float,
    Quantity float,
    RejectOrderID varchar(128),
    RejectReason varchar(128),
    ReplaceOrderID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    StopLimitPrice float,
    TimeInForce varchar(128),
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePBData varchar(8000),
    FundDeskOrderAllocations varchar(8000),
    InternalOrderAckID varchar(128),
    InternalOrderAmendID varchar(128),
    InternalOrderCancelID varchar(128),
    OrderDate date,
    OrderEventReason varchar(128),
    OrderEventType varchar(128),
    OrderState varchar(128),
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    SwapIndicator bigint,
    OriginalOrderUUID varchar(128),
    RootOrderUUID varchar(128),
    TradeDate date,
    ElysiumRevisionNumber bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Executions_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    BookingEligible bigint,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DirectedOrderIndicator bigint,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice bigint,
    IsInternal bigint,
    IsSolicited bigint,
    LastCapacity varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    SwapIndicator bigint,
    TradeDate date,
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    TransactionToBeCleared bigint,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    VersionNumber varchar(128),
    WaiverIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Enrichments
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    RecordType varchar(128),
    "UUID" varchar(128),
    EventTime bigint NOT NULL,
    OriginatorSystem varchar(128),
    VersionNumber varchar(128),
    financeTrader varchar(128),
    financeTraderType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    OriginatorSubsystem varchar(128),
    OTCIndicator varchar(128),
    OTCAPAIndicator varchar(128),
    WaiverIndicator varchar(128),
    BookingEligible bigint,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DirectedOrderIndicator bigint,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutionInstructions varchar(256),
    ExternalExecutionID varchar(128),
    InstrumentID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    IsEstimatedPrice bigint,
    IsInternal bigint,
    IsSolicited bigint,
    LastCapacity varchar(128),
    LinkID varchar(128),
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OriginatorLocation varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    SwapIndicator bigint,
    TradeDate date,
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    TransactionToBeCleared bigint,
    VenueIdentifier varchar(128),
    VenueType varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    CommissionType varchar(128),
    CommissionValue float,
    ElysiumStartDateTime timestamptz,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    financePBData varchar(8000),
    financeQuantity float,
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    OrderUUID varchar(128),
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    TradeType varchar(128),
    CancelledExecutionUUID varchar(128),
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Enrichments_Rejected
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONTENT varchar(64000),
    REJECT_INDEX bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Busts_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    "UUID" varchar(128) NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    CancelledExecutionUUID varchar(128),
    CancelledQuantity float,
    EventTime bigint NOT NULL,
    EventTimeNsecs bigint,
    ExternalExecutionID varchar(128),
    InternalExecutionID varchar(128),
    InternalOrderID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TransactionTime bigint,
    TransactionTimeNsecs bigint,
    VersionNumber varchar(128),
    ElysiumStartDateTime timestamptz,
    SequenceInstance varchar(128),
    SequenceNumber bigint,
    AgencyClientID bigint,
    AggregationValue varchar(128),
    BookingEligible bigint,
    BookingMethod varchar(128),
    BrokerOrderID varchar(128),
    BrokerSettlementDate date,
    financeBusinessUnit varchar(128),
    financeBusinessUnitType varchar(128),
    financeDesk varchar(128),
    financeDeskType varchar(128),
    financeFundID bigint,
    financeJoinID varchar(128),
    financeJoinIDType varchar(128),
    financePB varchar(128),
    financePBData varchar(8000),
    financePBType varchar(128),
    financeQuantity float,
    financeTrader varchar(128),
    financeTraderType varchar(128),
    ClearingAccount varchar(128),
    ClearingAccountType varchar(128),
    ClearingBroker varchar(128),
    ClearingBrokerType varchar(128),
    CommissionCurrencyID bigint,
    CommissionData varchar(8000),
    CommissionType varchar(128),
    CommissionValue float,
    ConnectionID varchar(128),
    ConnectionName varchar(128),
    ConnectionType varchar(128),
    ConnectionUKey bigint,
    DirectedOrderIndicator bigint,
    DiscretionaryPrice float,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    ExecQuantity float,
    ExecQuantityType varchar(128),
    ExecutingAccount varchar(128),
    ExecutingAccountType varchar(128),
    ExecutingBroker varchar(128),
    ExecutingBrokerType varchar(128),
    ExecutingCapacity varchar(128),
    ExecutingType varchar(128),
    FundDeskExecAllocations varchar(8000),
    FutureType varchar(128),
    FXBuyCurrencyID bigint,
    FXBuyQuantity float,
    FXSellCurrencyID bigint,
    FXSellQuantity float,
    InstrumentID varchar(128),
    InstrumentIDType varchar(128),
    InvestmentDecisionWithinFirm varchar(128),
    InvestmentDecisionWithinFirmType varchar(128),
    IsEstimatedPrice bigint,
    IsInternal bigint,
    IsSolicited bigint,
    LastCapacity varchar(128),
    LimitPrice float,
    LinkedTransactionCount bigint,
    LinkedTransactionIndex bigint,
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    LocateAmount float,
    LocateBroker varchar(128),
    LocateBrokerType varchar(128),
    MaxFloor float,
    OptionOpenClose varchar(128),
    OrderAction varchar(128),
    OrderUUID varchar(128),
    OriginatorLocation varchar(128),
    OTCAPAIndicator varchar(128),
    OTCIndicator varchar(128),
    RegulatoryExemptionIndicator varchar(128),
    RegulatoryTradeID varchar(128),
    ShortSellReportingExempt bigint,
    Side varchar(128),
    SwapIndicator bigint,
    TradeDate date,
    TradeType varchar(128),
    TransactionToBeCleared bigint,
    ElysiumRevisionNumber bigint,
    ExecutionType varchar(128),
    SourcePB varchar(128),
    RootOrderUUID varchar(128),
    TraderID bigint,
    POExecutionID varchar(128),
    SettlDate Date,
    PossResend bigint
);

CREATE TABLE IF NOT EXISTS Elysium.FINGAM_ComplexTrades
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EventTime bigint NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    ElysiumStartDateTime timestamptz,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    financeDeskType varchar(128),
    financeDesk varchar(128),
    "UUID" varchar(128),
    EventTimeNsecs bigint,
    ExecPrice float,
    ExecPriceCurrencyID bigint,
    ExecPriceType varchar(128),
    InternalComplexExecutionID varchar(128),
    LinkedTransactionType varchar(128),
    LinkID varchar(128),
    OriginatorSubsystem varchar(128),
    OriginatorSystem varchar(128),
    TradeDate date
);

CREATE TABLE IF NOT EXISTS Elysium.FINGAM_Orders_Rejected
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz DEFAULT CURRENT_TIMESTAMP,
    CONTENT varchar(64000),
    REJECT_INDEX bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS Elysium.Sweeper_Bookmark
(
    table_name varchar(128) NOT NULL,
    last_id bigint NOT NULL
);


CREATE TABLE IF NOT EXISTS sandbox.TKEY_LATEST_MAPPINGS_T
(
    ID bigint NOT NULL,
    CLOCK_TIMESTAMP timestamptz NOT NULL,
    ElysiumAMPSClientName varchar(128),
    ElysiumAMPSOrigin varchar(128),
    ElysiumAMPSTopic varchar(128),
    ElysiumAMPSYMDUUID varchar(128),
    ElysiumStartDateTime timestamptz,
    TxID bigint NOT NULL,
    "UUID" varchar(128) NOT NULL,
    RecordType varchar(128) NOT NULL,
    VersionNumber varchar(128) NOT NULL,
    EventTime bigint NOT NULL,
    BookingDate date,
    FirmID bigint,
    InternalExecutionID varchar(128),
    OriginatorSystem varchar(128),
    OriginatorSubsystem varchar(128)
);

CREATE TABLE IF NOT EXISTS sandbox.BookmarkStore_TO_DROP2
(
    flow varchar(128) NOT NULL,
    source varchar(128) NOT NULL,
    publisher varchar(32) NOT NULL,
    bookmark varchar(64) NOT NULL,
    batchId bigint NOT NULL,
    lastSeen bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS sandbox.BookmarkStore_TO_DROP
(
    flow varchar(128) NOT NULL,
    source varchar(128) NOT NULL,
    publisher varchar(32) NOT NULL,
    bookmark varchar(64) NOT NULL,
    batchId bigint NOT NULL,
    lastSeen bigint NOT NULL,
    active boolean NOT NULL DEFAULT true
);

/*Compliance*/
CREATE TABLE IF NOT EXISTS Compliance.DeskLevelUser
(
    UserName varchar(30) NOT NULL,
    FullName varchar(128) NOT NULL,
    DeskCode bigint NOT NULL,
    DeskUKEY varchar(128) NOT NULL,
    DeskNAME varchar(128) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS Compliance.OverTheEdgeUser
(
    UserName varchar(30) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS Compliance.OverTheEdgeUserDB
(
    UserName varchar(30) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS Compliance.DeskLevelUserDB
(
    UserName varchar(30) NOT NULL,
    FullName varchar(128) NOT NULL,
    DeskCode bigint NOT NULL,
    DeskUKEY varchar(128) NOT NULL,
    DeskNAME varchar(128) NOT NULL,
    MartModifiedDate timestamp NOT NULL
);
